# Generated by Django 5.2.5 on 2025-09-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(db_index=True, max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado')], default='Disponible', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('vence', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.libro')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
