# Generated by Django 5.2.5 on 2025-10-24 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_anio_libro_edicion_libro_editorial_libro_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado')], default='DISPONIBLE', max_length=10)),
            ],
            options={
                'ordering': ['titulo_id', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='alumno',
            new_name='alumno_nombre',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='devuelto',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='dni',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='alumno_dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('RENOVADO', 'Renovado'), ('VENCIDO', 'Vencido'), ('DEVUELTO', 'Devuelto')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.ejemplar'),
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('TRABAJO', 'Trabajo/Informe/Tesis/Monografía')], default='LIBRO', max_length=10)),
                ('lugar_edicion', models.CharField(blank=True, max_length=120)),
                ('editorial', models.CharField(blank=True, max_length=120)),
                ('anio', models.CharField(blank=True, max_length=10)),
                ('edicion', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('categorias', models.ManyToManyField(blank=True, related_name='titulos', to='core.categoria')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='core.titulo'),
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
